### ISSUE TITLE
Migration to v3

### ISSUE THREAD

**Issue by RafPe** [apiheat/akamai-cli-frn#1]
* All responses are JSON - we are engineers 
* Using dep for dependency management 
* Dep edgegrid client locked to v3.x.x 
* Using GoReleaser with brew config 
* Using TravisCI for builds 
* Akamai CLI reflects correct version and name of package
* Readme file updated to new standard

**Comment by partamonov** [comment]
Migrated to v3.

- [x] some replies are table formatted, but main ones are json

- [X] Using dep for dependency management

- [x] Dep edgegrid client locked to v3.x.x

- [x] Using GoReleaser with brew config - brew abolished

- [x] Using TravisCI for builds

- [x] Akamai CLI reflects correct version and name of package

- [x] Readme file updated to new standard
